### ISSUE TITLE
Ctrl+Click conflicts with "multi-cursor" functionnality

### ISSUE THREAD

**Issue by Arcesilas** [Gert-dev/php-integrator-navigation#15]
using Ctrl+Click works very fine no navigate. However, I've noticed some strange behaviours it took me quite some time to understand.

When Ctrl+Clicking in a page, Atom adds a nex cursor which allow to type the same thing at different places. This can be convenient (I don't know in which cases and if anyone really uses it) but when using Ctrl key to navigate, when jumping, it leaves another cursor.
If you don't take care, when coming back to the previous file, you have 2 cursors. And you start typing duplicate code.

Would there be a way to avoid the second cursor when jumping with Ctrl key ?

It's not a bug, but it's not a feature: it's a bit annoying, that's all.

Thanks anyway for your reactivity!

**Comment by Gert-dev** [comment]
I've noticed the same. This is the primary reason the default shortcut is alt-click, instead of the more common control-click. Originally it also wasn't possible to change alt-click into something else, but I've made the modifier key (control, shift, alt and meta) configurable via the settings screen due to popular request.

For now you can try any of the other modifier keys (or a combination of them, such as ctrl-alt-click). The ideal solution would be that Atom makes the mouse clicks configurable, as it does your keymap. This would allow you to decide exactly what kind of behavior you want. I also quickly tried some of the conventional means of stopping the click from propagating, but that doesn't seem to influence this problem.

**Comment by Gert-dev** [comment]
I'll close this since there isn't really anything I can do about it at this point. I'll keep a look-out if Atom adds support in case there is something I need to do on my side to support it.
