### ISSUE TITLE
Ability to change alt-click to use another key modifier.

### ISSUE THREAD

**Issue by yahyaerturan** [Gert-dev/php-integrator-navigation#4]
In my laravel project, I pressed alt and it highlights but when I clicked there is no action. I am using Ubuntu 14.14 LTS. Any idea?

**Comment by Alphanumerix** [comment]
I'm not Ubuntu User, but maybe "alt+click (and move)" is a shortcut for moving window?
Same problem in Arch Linux with OpenBox and KDE/Plasma.
Quick solution is to make your Dekstop Envivorment move window with anything, but alt-click.

The problem in our case is "alt-clicking". It would be nice, if it would be configurable (meta-clicking?).

**Comment by yahyaerturan** [comment]
How can we overwrite the atom key binding?

**Comment by Alphanumerix** [comment]
I'm not sure if it's possible for this package, but generally it can be done by editing keymap file.
Go to Settings -> Keybindings and click "your keymap file". It will open keymap file, where you can define your own keybindings.

**Comment by tocjent** [comment]
I'm using the package with Ubuntu GNOME 15.10 and alt+click also doesn't work, but I would suggest trying ctrl + alt + click, as alt+click function is moving windows around in Ubuntu.

**Comment by Gert-dev** [comment]
Whenever alt-click underlines but does nothing on click, it means that the method wasn't found or its location can't be determined. This either happens due to a bug in the base package or because indexing is not happening properly (e.g. due to code not properly using namespaces).

I do understand that alt-click may not be desirable for everyone. This was done because it's consistent with other packages (such as hyperclick). It can't be rebound using the keymap as it's not actually a key press; a mouse click is happening instead (with a check for the alt key being pressed during that click). I may take a look at making this modifier key modifyable, but I'll have to investigate whether it's possible to use the meta key for this (on Linux).

**Comment by Alphanumerix** [comment]
I believe that issue title should be changed.

**Comment by Gert-dev** [comment]
Agreed.

**Comment by Alphanumerix** [comment]
Latest discovery - for me navigation works when using `alt`+(`meta` or `ctrl` or `shift`)+`left click`, which is funky, but totally predictable - Desktop Environment does not recognize short-cut any more, but Atom itself does.

**Comment by Gert-dev** [comment]
This will be present in the next release 0.4.0 (along with base package 0.5.0).

**Comment by Alphanumerix** [comment]
Nice to hear. Looking forward for update :)
